apiVersion: v1
kind: ReplicationController
metadata:
  name: nfs-bucket-server
spec:
  replicas: 1
  selector:
    role: nfs-bucket-server
  template:
    metadata:
      labels:
        role: nfs-bucket-server
    spec:
      volumes:
        - name: sa-THE-SERVICE-ACCOUNT
          secret:
            secretName: sa-THE-SERVICE-ACCOUNT
      containers:
      - name: nfs-bucket-server
        image: anderselton/nfs-bucket-server:latest
        env:
        - name: BUCKET
          value: "CHANGE-ME"
        ports:
          - name: nfs
            containerPort: 2049
          - name: mountd
            containerPort: 20048
          - name: rpcbind
            containerPort: 111
        volumeMounts:
          - name: sa-THE-SERVICE-ACCOUNT
            mountPath: "/accounts"
            readOnly: true
        securityContext:
          privileged: true
